// Generated by JFlex 1.9.2 http://jflex.de/  (tweaked for IntelliJ platform)
// source: src/main/java/com/dream/DreamLexer.flex

package com.dream;


public class DreamLexer implements com.intellij.lexer.FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\1\1\1\2\1\3\2\4\1\3\22\0\1\2"+
    "\1\5\1\6\2\0\1\5\1\7\1\0\2\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\12\17\1\0\1\20"+
    "\1\21\1\22\1\23\1\24\1\0\2\25\1\26\10\25"+
    "\1\27\5\25\1\30\1\31\3\25\1\32\3\25\1\33"+
    "\1\34\1\35\1\36\1\25\1\0\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\25\1\50"+
    "\1\51\1\25\1\52\1\53\2\25\1\54\1\55\1\56"+
    "\1\57\1\60\1\61\3\25\1\62\1\63\1\62\1\64"+
    "\6\0\1\4\u01a2\0\2\4\326\0\u0100\4";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\1\3\1\1\1\3\1\4\1\5"+
    "\2\3\1\6\2\3\1\7\1\10\1\3\21\0\1\11"+
    "\2\0\1\12\1\13\3\3\1\14\1\0\1\15\45\0"+
    "\1\16\52\0\1\17\5\0\1\20";

  private static int [] zzUnpackAction() {
    int [] result = new int[132];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\u0109\0\u013e\0\65"+
    "\0\65\0\u0173\0\u01a8\0\65\0\u01dd\0\u0212\0\u0247\0\65"+
    "\0\65\0\u027c\0\u02b1\0\u02e6\0\u031b\0\u0350\0\u0385\0\u03ba"+
    "\0\u03ef\0\u0424\0\u0459\0\u048e\0\u04c3\0\u04f8\0\u052d\0\u0562"+
    "\0\u0597\0\u0109\0\65\0\u05cc\0\u0601\0\u0636\0\65\0\u066b"+
    "\0\u06a0\0\u06d5\0\65\0\u070a\0\65\0\u073f\0\u0774\0\u07a9"+
    "\0\u07de\0\u0813\0\u0848\0\u087d\0\u08b2\0\u08e7\0\u091c\0\u0951"+
    "\0\u0986\0\u09bb\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9"+
    "\0\u0b2e\0\u0b63\0\u0b98\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c\0\u0ca1"+
    "\0\u0cd6\0\u0d0b\0\u0d40\0\u0d75\0\u0daa\0\u0ddf\0\u0e14\0\u0e49"+
    "\0\u0e7e\0\u0eb3\0\65\0\u0ee8\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc"+
    "\0\u0ff1\0\u1026\0\u105b\0\u1090\0\u10c5\0\u10fa\0\u112f\0\u1164"+
    "\0\u1199\0\u11ce\0\u1203\0\u1238\0\u126d\0\u12a2\0\u12d7\0\u130c"+
    "\0\u1341\0\u1376\0\u13ab\0\u13e0\0\u1415\0\u144a\0\u147f\0\u14b4"+
    "\0\u14e9\0\u151e\0\u1553\0\u1588\0\u15bd\0\u15f2\0\u1627\0\u165c"+
    "\0\u1691\0\u16c6\0\u16fb\0\u1730\0\u1765\0\65\0\u179a\0\u17cf"+
    "\0\u1804\0\u1839\0\u186e\0\65";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[132];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\0\1\5\1\6\1\7\1\10"+
    "\2\2\1\11\1\12\1\2\1\13\1\2\1\14\1\15"+
    "\1\5\1\16\10\2\1\17\25\2\1\20\1\2\1\21"+
    "\104\0\1\22\5\0\1\23\1\24\1\23\1\25\1\23"+
    "\1\26\4\0\1\23\1\27\1\30\1\31\1\32\1\33"+
    "\2\23\1\34\4\23\1\35\1\36\1\37\1\23\1\40"+
    "\1\41\5\0\2\4\103\0\1\21\42\0\6\42\1\43"+
    "\25\42\1\44\15\42\1\0\12\42\7\0\1\21\12\0"+
    "\1\21\56\0\1\21\5\0\1\21\53\0\1\45\4\0"+
    "\1\46\3\0\1\21\63\0\1\5\1\21\64\0\1\21"+
    "\1\5\41\0\3\47\2\0\4\47\1\5\1\50\11\47"+
    "\1\51\11\47\1\5\24\47\1\52\1\47\1\0\1\53"+
    "\15\0\1\22\14\0\1\54\31\0\1\55\15\0\1\23"+
    "\5\0\6\23\4\0\23\23\4\0\1\55\15\0\1\23"+
    "\5\0\6\23\4\0\14\23\1\56\6\23\4\0\1\55"+
    "\15\0\1\23\5\0\6\23\4\0\4\23\1\57\16\23"+
    "\4\0\1\55\15\0\1\23\5\0\6\23\4\0\15\23"+
    "\1\60\5\23\4\0\1\55\15\0\1\23\5\0\6\23"+
    "\4\0\14\23\1\61\1\62\5\23\4\0\1\55\15\0"+
    "\1\23\5\0\6\23\4\0\1\63\6\23\1\64\2\23"+
    "\1\65\1\23\1\66\6\23\4\0\1\55\15\0\1\23"+
    "\5\0\6\23\4\0\4\23\1\67\7\23\1\70\6\23"+
    "\4\0\1\55\15\0\1\23\5\0\6\23\4\0\12\23"+
    "\1\63\10\23\4\0\1\55\15\0\1\23\5\0\6\23"+
    "\4\0\1\32\11\23\1\71\1\23\1\72\3\23\1\73"+
    "\2\23\4\0\1\55\15\0\1\23\5\0\6\23\4\0"+
    "\5\23\1\70\5\23\1\74\7\23\4\0\1\55\15\0"+
    "\1\23\5\0\6\23\4\0\4\23\1\75\16\23\4\0"+
    "\1\55\15\0\1\23\5\0\6\23\4\0\17\23\1\76"+
    "\2\23\1\77\4\0\1\55\15\0\1\23\5\0\6\23"+
    "\4\0\15\23\1\100\5\23\4\0\1\55\15\0\1\23"+
    "\5\0\6\23\4\0\1\72\13\23\1\101\6\23\4\0"+
    "\1\55\15\0\1\23\5\0\6\23\4\0\7\23\1\102"+
    "\13\23\37\0\1\103\41\0\1\104\21\0\1\105\31\0"+
    "\3\46\2\0\60\46\22\0\1\21\11\0\1\106\64\0"+
    "\1\107\52\0\1\21\11\0\1\110\30\0\3\111\2\0"+
    "\60\111\1\0\1\55\15\0\1\23\5\0\6\23\4\0"+
    "\13\23\1\112\7\23\4\0\1\55\15\0\1\23\5\0"+
    "\6\23\4\0\1\113\22\23\4\0\1\55\15\0\1\23"+
    "\5\0\6\23\4\0\10\23\1\114\12\23\4\0\1\55"+
    "\15\0\1\23\5\0\6\23\4\0\14\23\1\115\6\23"+
    "\4\0\1\55\15\0\1\23\5\0\6\23\4\0\4\23"+
    "\1\116\16\23\4\0\1\55\15\0\1\23\5\0\6\23"+
    "\4\0\16\23\1\117\4\23\4\0\1\55\15\0\1\23"+
    "\5\0\6\23\4\0\1\72\22\23\4\0\1\55\15\0"+
    "\1\23\5\0\6\23\4\0\1\120\22\23\4\0\1\55"+
    "\15\0\1\23\5\0\6\23\4\0\13\23\1\121\7\23"+
    "\4\0\1\55\15\0\1\23\5\0\6\23\4\0\5\23"+
    "\1\122\15\23\4\0\1\123\15\0\1\23\5\0\6\23"+
    "\4\0\23\23\4\0\1\55\15\0\1\23\5\0\6\23"+
    "\4\0\14\23\1\124\6\23\4\0\1\55\15\0\1\23"+
    "\5\0\6\23\4\0\15\23\1\70\5\23\4\0\1\55"+
    "\15\0\1\23\5\0\6\23\4\0\13\23\1\125\7\23"+
    "\4\0\1\55\15\0\1\23\5\0\6\23\4\0\17\23"+
    "\1\70\3\23\4\0\1\55\15\0\1\23\5\0\6\23"+
    "\4\0\17\23\1\126\3\23\4\0\1\55\15\0\1\23"+
    "\5\0\6\23\4\0\15\23\1\127\5\23\4\0\1\55"+
    "\15\0\1\23\5\0\6\23\4\0\10\23\1\130\12\23"+
    "\4\0\1\55\15\0\1\23\5\0\6\23\4\0\20\23"+
    "\1\117\2\23\4\0\1\55\15\0\1\23\5\0\6\23"+
    "\4\0\10\23\1\131\12\23\4\0\1\55\15\0\1\23"+
    "\5\0\6\23\4\0\10\23\1\132\12\23\3\0\3\42"+
    "\2\0\60\42\33\0\1\133\106\0\1\134\21\0\1\21"+
    "\76\0\1\5\123\0\1\21\20\0\1\135\46\0\1\55"+
    "\15\0\1\23\5\0\6\23\4\0\16\23\1\136\4\23"+
    "\4\0\1\55\15\0\1\23\5\0\6\23\4\0\3\23"+
    "\1\137\17\23\4\0\1\55\15\0\1\23\5\0\6\23"+
    "\4\0\17\23\1\140\3\23\4\0\1\55\15\0\1\23"+
    "\5\0\6\23\4\0\12\23\1\70\10\23\4\0\1\55"+
    "\15\0\1\23\5\0\6\23\4\0\1\141\22\23\4\0"+
    "\1\55\15\0\1\23\5\0\6\23\4\0\4\23\1\70"+
    "\16\23\4\0\1\55\15\0\1\23\5\0\6\23\4\0"+
    "\16\23\1\142\4\23\4\0\1\55\15\0\1\23\5\0"+
    "\6\23\4\0\17\23\1\143\3\23\4\0\1\55\15\0"+
    "\1\23\5\0\6\23\4\0\1\144\22\23\4\0\1\55"+
    "\15\0\1\23\5\0\6\23\4\0\1\74\22\23\4\0"+
    "\1\55\15\0\1\23\5\0\6\23\4\0\2\23\1\70"+
    "\20\23\4\0\1\55\15\0\1\23\5\0\6\23\4\0"+
    "\20\23\1\145\2\23\4\0\1\55\15\0\1\23\5\0"+
    "\6\23\4\0\10\23\1\146\7\23\1\147\2\23\4\0"+
    "\1\55\15\0\1\23\5\0\6\23\4\0\17\23\1\150"+
    "\3\23\4\0\1\55\15\0\1\23\5\0\6\23\4\0"+
    "\3\23\1\70\17\23\4\0\1\55\15\0\1\23\5\0"+
    "\6\23\4\0\12\23\1\117\10\23\41\0\1\151\57\0"+
    "\1\152\34\0\1\53\15\0\1\135\46\0\1\55\15\0"+
    "\1\23\5\0\6\23\4\0\14\23\1\132\6\23\4\0"+
    "\1\55\15\0\1\23\5\0\2\23\1\153\3\23\4\0"+
    "\23\23\4\0\1\55\15\0\1\23\5\0\6\23\4\0"+
    "\4\23\1\154\16\23\4\0\1\55\15\0\1\23\5\0"+
    "\6\23\4\0\11\23\1\70\11\23\4\0\1\55\15\0"+
    "\1\23\5\0\6\23\4\0\16\23\1\70\4\23\4\0"+
    "\1\55\15\0\1\23\5\0\6\23\4\0\10\23\1\155"+
    "\12\23\4\0\1\55\15\0\1\23\5\0\6\23\4\0"+
    "\20\23\1\156\2\23\4\0\1\55\15\0\1\23\5\0"+
    "\6\23\4\0\15\23\1\157\5\23\4\0\1\55\15\0"+
    "\1\23\5\0\6\23\4\0\13\23\1\160\7\23\4\0"+
    "\1\55\15\0\1\23\5\0\6\23\4\0\2\23\1\74"+
    "\20\23\4\0\1\55\15\0\1\23\5\0\6\23\4\0"+
    "\2\23\1\161\20\23\40\0\1\162\64\0\1\163\30\0"+
    "\1\55\15\0\1\23\5\0\6\23\4\0\10\23\1\164"+
    "\12\23\4\0\1\123\15\0\1\23\5\0\2\23\1\153"+
    "\3\23\4\0\23\23\4\0\1\55\15\0\1\23\5\0"+
    "\6\23\4\0\13\23\1\100\7\23\4\0\1\55\15\0"+
    "\1\23\5\0\6\23\4\0\12\23\1\74\10\23\4\0"+
    "\1\55\15\0\1\23\5\0\6\23\4\0\13\23\1\70"+
    "\7\23\4\0\1\55\15\0\1\23\5\0\6\23\4\0"+
    "\6\23\1\70\14\23\4\0\1\55\15\0\1\23\5\0"+
    "\6\23\4\0\7\23\1\70\13\23\14\0\1\165\64\0"+
    "\1\166\54\0\1\55\15\0\1\23\5\0\6\23\4\0"+
    "\13\23\1\117\7\23\27\0\1\167\64\0\1\170\74\0"+
    "\1\171\64\0\1\172\41\0\1\173\64\0\1\174\71\0"+
    "\1\175\64\0\1\176\131\0\1\177\17\0\1\200\64\0"+
    "\1\201\64\0\1\202\63\0\1\203\60\0\1\204\53\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6307];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\2\11\2\1\1\11\3\1\2\11"+
    "\21\0\1\11\2\0\1\1\1\11\3\1\1\11\1\0"+
    "\1\11\45\0\1\11\52\0\1\11\5\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[132];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public DreamLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public com.intellij.psi.tree.IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return com.intellij.psi.TokenType.BAD_CHARACTER;
            }
          // fall through
          case 17: break;
          case 2:
            { return com.intellij.psi.TokenType.WHITE_SPACE;
            }
          // fall through
          case 18: break;
          case 3:
            { return DreamTokenTypes.OPERATOR;
            }
          // fall through
          case 19: break;
          case 4:
            { return DreamTokenTypes.PAREN;
            }
          // fall through
          case 20: break;
          case 5:
            { return DreamTokenTypes.COMMA;
            }
          // fall through
          case 21: break;
          case 6:
            { return DreamTokenTypes.SEMICOLON;
            }
          // fall through
          case 22: break;
          case 7:
            { return DreamTokenTypes.BRACKET;
            }
          // fall through
          case 23: break;
          case 8:
            { return DreamTokenTypes.BRACE;
            }
          // fall through
          case 24: break;
          case 9:
            { return DreamTokenTypes.STRING;
            }
          // fall through
          case 25: break;
          case 10:
            { return DreamTokenTypes.COMMENT;
            }
          // fall through
          case 26: break;
          case 11:
            { return DreamTokenTypes.DOT;
            }
          // fall through
          case 27: break;
          case 12:
            { return DreamTokenTypes.NUMBER;
            }
          // fall through
          case 28: break;
          case 13:
            { return DreamTokenTypes.IDENTIFIER;
            }
          // fall through
          case 29: break;
          case 14:
            { return DreamTokenTypes.KEYWORD;
            }
          // fall through
          case 30: break;
          case 15:
            { return DreamTokenTypes.COMMENTBLOCK;
            }
          // fall through
          case 31: break;
          case 16:
            { return DreamTokenTypes.COMMENTDOC;
            }
          // fall through
          case 32: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
