// Placeholder DFA table generated by lexgen.zig
#ifndef DFA_TABLE_H
#define DFA_TABLE_H
#include <stdint.h>

typedef enum {
    TOKEN_EOF,
    TOKEN_UNKNOWN
} TokenType;

static const uint16_t DFA[][256] = { {0} };

#endif // DFA_TABLE_H
