#ifndef LEXER_H
#define LEXER_H

#include <stdio.h>

typedef enum {
  TOKEN_INT,
  TOKEN_STRING_TYPE,
  TOKEN_BOOL_TYPE,
  TOKEN_FLOAT_TYPE,
  TOKEN_CHAR_TYPE,
  TOKEN_IDENTIFIER,
  TOKEN_NUMBER,
  TOKEN_STRING,
  TOKEN_CHAR,
  TOKEN_PLUS,
  TOKEN_MINUS,
  TOKEN_PLUSPLUS,
  TOKEN_MINUSMINUS,
  TOKEN_PLUSEQ,
  TOKEN_MINUSEQ,
  TOKEN_STAR,
  TOKEN_SLASH,
  TOKEN_PERCENT,
  TOKEN_STAREQ,
  TOKEN_SLASHEQ,
  TOKEN_MODEQ,
  TOKEN_LT,
  TOKEN_GT,
  TOKEN_LE,
  TOKEN_GE,
  TOKEN_EQEQ,
  TOKEN_NEQ,
  TOKEN_NOT,
  TOKEN_BITNOT,
  TOKEN_AND,
  TOKEN_OR,
  TOKEN_BITAND,
  TOKEN_BITOR,
  TOKEN_CARET,
  TOKEN_SHL,
  TOKEN_SHR,
  TOKEN_QUESTION,
  TOKEN_SEMICOLON,
  TOKEN_COLON,
  TOKEN_EQUALS,
  TOKEN_CONSOLE,
  TOKEN_DOT,
  TOKEN_WRITELINE,
  TOKEN_WRITE,
  TOKEN_LPAREN,
  TOKEN_RPAREN,
  TOKEN_COMMA,
  TOKEN_IF,
  TOKEN_ELSE,
  TOKEN_WHILE,
  TOKEN_FOR,
  TOKEN_SWITCH,
  TOKEN_CASE,
  TOKEN_DEFAULT,
  TOKEN_DO,
  TOKEN_BREAK,
  TOKEN_CONTINUE,
  TOKEN_RETURN,
  TOKEN_FUNC,
  TOKEN_CLASS,
  TOKEN_STRUCT,
  TOKEN_LBRACE,
  TOKEN_RBRACE,
  TOKEN_EOF,
  TOKEN_UNKNOWN
} TokenType;

typedef struct {
  TokenType type;
  char *value;
} Token;

typedef struct {
  char *source;
  int pos;
  int line;
} Lexer;

Token next_token(Lexer *lexer);

#endif
