name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential make gdb re2c
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install -y make mingw re2c
      - name: Build
        run: zig build
      - name: Run tests
        run: python codex/python/test_runner
        shell: bash
